CREATE DATABASE SIEUTHIDIENMAY

CREATE TABLE POSITION
(
ID INT NOT NULL PRIMARY KEY
,NAME NVARCHAR(50)
);

CREATE TABLE DEPARTMENT
(
ID INT NOT NULL PRIMARY KEY
,NAME NVARCHAR(50)
);

CREATE TABLE EMPLOYEES
(
ID INT NOT NULL PRIMARY KEY
,NAME NVARCHAR(50)
,DATE NVARCHAR(50)
,SALARY INT
,POSITION_ID INT NOT NULL
,DEPART_ID INT NOT NULL
);

ALTER TABLE EMPLOYEES ADD FOREIGN KEY(POSITION_ID) REFERENCES POSITION(ID)
ALTER TABLE EMPLOYEES ADD FOREIGN KEY(DEPART_ID) REFERENCES DEPARTMENT(ID)

