CREATE DATABASE SIEUTHIDIENMAY

CREATE TABLE TYPES
(
ID INT NOT NULL PRIMARY KEY
,NAME NVARCHAR(50)
,IMG NVARCHAR(100)
);

CREATE TABLE MANUFACTURES
(
ID INT NOT NULL PRIMARY KEY
,NAME NVARCHAR(50)
,DESCRIBE NVARCHAR(200)
,IMG NVARCHAR(100)
);

CREATE TABLE PRODUCTS
(
ID INT NOT NULL PRIMARY KEY
,NAME NVARCHAR(50)
,DESCRIBE NVARCHAR(200)
,PRICE MONEY
,TYPE_ID INT NOT NULL
,MANU_ID  INT NOT NULL
);

ALTER TABLE PRODUCTS ADD FOREIGN KEY(TYPE_ID) REFERENCES TYPES(ID)

ALTER TABLE PRODUCTS ADD FOREIGN KEY(MANU_ID) REFERENCES MANUFACTURES(ID)

